"""split job_category into many-to-many job_categories

Revision ID: 1988a378b152
Revises: b366dfcdf790
Create Date: 2026-08-20 11:47:14.989909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1988a378b152'
down_revision: Union[str, Sequence[str], None] = 'b366dfcdf790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_job_categories_id'), 'job_categories', ['id'], unique=False)
    op.create_table('job_posting_categories',
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['job_categories.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('job_posting_id', 'category_id')
    )
    op.drop_index(op.f('ix_job_postings_job_category'), table_name='job_postings')
    op.drop_column('job_postings', 'job_category')
    # ### end Alembic commands ###
    # NOTE: job_indexes/job_details 관련 인덱스·제약조건 이름 잡음(과거 jobs_raw 잔재)은
    # 이 마이그레이션과 무관하므로 건드리지 않음


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('job_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_job_postings_job_category'), 'job_postings', ['job_category'], unique=False)
    op.drop_table('job_posting_categories')
    op.drop_index(op.f('ix_job_categories_id'), table_name='job_categories')
    op.drop_table('job_categories')
    # ### end Alembic commands ###
