"""drop legacy job_indexes and job_details tables

Revision ID: 8bcf29644e82
Revises: 99b00f59275a
Create Date: 2026-08-25 15:32:15.952021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bcf29644e82'
down_revision: Union[str, Sequence[str], None] = '99b00f59275a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_indexes')
    op.drop_table('job_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('job_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tech_stack', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('href', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_failed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_table('job_indexes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rec_idx', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('href', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('job_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_crawled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('crawled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_failed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_raw_pkey')),
    sa.UniqueConstraint('rec_idx', 'job_name', name=op.f('jobs_raw_rec_idx_job_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
