"""add keyword_extracted_at to job_postings

Revision ID: 99b00f59275a
Revises: 1988a378b152
Create Date: 2026-08-21 13:04:49.694317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b00f59275a'
down_revision: Union[str, Sequence[str], None] = '1988a378b152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('keyword_extracted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'keyword_extracted_at')
    # ### end Alembic commands ###
